### ISSUE TITLE
extract weights model_3/4/5 error

### ISSUE THREAD

**Issue by itsme334** [IntelLabs/open-omics-alphafold#6]
Hi,
when extract weights in the <root_home> directory with params_model_3.npz、params_model_4.npz or params_model_5.npz，not working.
```
(iaf2)$ python extract_params.py --input <mydata>/params/params_model_3.npz --output_dir ./weights/extracted/model_3
Traceback (most recent call last):
  File "<myroot_home>/extract_params.py", line 47, in <module>
    fix_name_issue(root_issue)
  File "<myroot_home>/extract_params.py", line 31, in fix_name_issue
    assert os.path.isdir(src_subdir)
AssertionError
```
but,when run  
```
(iaf2)$ python extract_params.py --input <mydata>/params/params_model_1.npz --output_dir ./weights/extracted/model_1
```
It's working.

**Comment by narendrachaudhary51** [comment]
Please pull the latest changes from the main branch. This issue has been fixed recently.

**Comment by itsme334** [comment]
Great, it worked. Did the test next.
